### ISSUE TITLE
error when installing LOCK

### ISSUE THREAD

**Issue by jacky50403** [tssailzz8/MyPlugins#24]
get following in ```dalamud.log``` when installing
```022-08-28 00:09:31.097 +08:00 [INF] [PLUGINM] Installed plugin Lock (testing=False)
2022-08-28 00:09:31.097 +08:00 [INF] [PLUGINM] Loading plugin Lock
2022-08-28 00:09:31.190 +08:00 [INF] [LOCALPLUGIN] Loading Lock.dll
2022-08-28 00:09:31.195 +08:00 [ERR] Command /LockBOSS is already registered.
2022-08-28 00:09:31.379 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wOC0yOFQwMDowOTozMS4zNzkxNDM4KzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5LZXlOb3RGb3VuZEV4Y2VwdGlvbjogQ2FuJ3QgZmluZCBhIHNpZ25hdHVyZSBvZiA0OCA4QiAwMSAzOCA1MCAwQyBcclxuICAgYXQgRGFsYW11ZC5HYW1lLlNpZ1NjYW5uZXIuU2NhblRleHQoU3RyaW5nIHNpZ25hdHVyZSkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcR2FtZVxcU2lnU2Nhbm5lci5jczpsaW5lIDMxMFxyXG4gICBhdCBMb2NrLlBsdWdpbi4uY3RvcihEYWxhbXVkUGx1Z2luSW50ZXJmYWNlIHBsdWdpbkludGVyZmFjZSwgRnJhbWV3b3JrIGZyYW1ld29yaywgQ29tbWFuZE1hbmFnZXIgY29tbWFuZE1hbmFnZXIsIFNpZ1NjYW5uZXIgc2lnU2Nhbm5lciwgQ2xpZW50U3RhdGUgY2xpZW50U3RhdGUpXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICBhdCBTeXN0ZW0uUnVudGltZU1ldGhvZEhhbmRsZS5JbnZva2VNZXRob2QoT2JqZWN0IHRhcmdldCwgU3BhbmAxJiBhcmd1bWVudHMsIFNpZ25hdHVyZSBzaWcsIEJvb2xlYW4gY29uc3RydWN0b3IsIEJvb2xlYW4gd3JhcEV4Y2VwdGlvbnMpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLlJ1bnRpbWVDb25zdHJ1Y3RvckluZm8uSW52b2tlKE9iamVjdCBvYmosIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyLCBCaW5kZXIgYmluZGVyLCBPYmplY3RbXSBwYXJhbWV0ZXJzLCBDdWx0dXJlSW5mbyBjdWx0dXJlKVxyXG4gICBhdCBEYWxhbXVkLklvQy5JbnRlcm5hbC5TZXJ2aWNlQ29udGFpbmVyLkNyZWF0ZUFzeW5jKFR5cGUgb2JqZWN0VHlwZSwgT2JqZWN0W10gc2NvcGVkT2JqZWN0cykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW9DXFxJbnRlcm5hbFxcU2VydmljZUNvbnRhaW5lci5jczpsaW5lIDEwN1xyXG4gICBhdCBEYWxhbXVkLlBsdWdpbi5JbnRlcm5hbC5UeXBlcy5Mb2NhbFBsdWdpbi5Mb2FkQXN5bmMoUGx1Z2luTG9hZFJlYXNvbiByZWFzb24sIEJvb2xlYW4gcmVsb2FkaW5nKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxQbHVnaW5cXEludGVybmFsXFxUeXBlc1xcTG9jYWxQbHVnaW4uY3M6bGluZSA0MTYiLCJDb250ZXh0IjoiW0xPQ0FMUExVR0lOXSBFcnJvciB3aGlsZSBsb2FkaW5nIExvY2sifQ==
2022-08-28 00:09:31.378 +08:00 [ERR] [LOCALPLUGIN] Error while loading Lock
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: Can't find a signature of 48 8B 01 38 50 0C 
   at Dalamud.Game.SigScanner.ScanText(String signature) in C:\goatsoft\companysecrets\dalamud\Game\SigScanner.cs:line 310
   at Lock.Plugin..ctor(DalamudPluginInterface pluginInterface, Framework framework, CommandManager commandManager, SigScanner sigScanner, ClientState clientState)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 107
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 416
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 792
2022-08-28 00:09:31.379 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wOC0yOFQwMDowOTozMS4zNzk3Mzk5KzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5SZWZsZWN0aW9uLlRhcmdldEludm9jYXRpb25FeGNlcHRpb246IEV4Y2VwdGlvbiBoYXMgYmVlbiB0aHJvd24gYnkgdGhlIHRhcmdldCBvZiBhbiBpbnZvY2F0aW9uLlxyXG4gLS0tPiBTeXN0ZW0uQ29sbGVjdGlvbnMuR2VuZXJpYy5LZXlOb3RGb3VuZEV4Y2VwdGlvbjogQ2FuJ3QgZmluZCBhIHNpZ25hdHVyZSBvZiA0OCA4QiAwMSAzOCA1MCAwQyBcclxuICAgYXQgRGFsYW11ZC5HYW1lLlNpZ1NjYW5uZXIuU2NhblRleHQoU3RyaW5nIHNpZ25hdHVyZSkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcR2FtZVxcU2lnU2Nhbm5lci5jczpsaW5lIDMxMFxyXG4gICBhdCBMb2NrLlBsdWdpbi4uY3RvcihEYWxhbXVkUGx1Z2luSW50ZXJmYWNlIHBsdWdpbkludGVyZmFjZSwgRnJhbWV3b3JrIGZyYW1ld29yaywgQ29tbWFuZE1hbmFnZXIgY29tbWFuZE1hbmFnZXIsIFNpZ1NjYW5uZXIgc2lnU2Nhbm5lciwgQ2xpZW50U3RhdGUgY2xpZW50U3RhdGUpXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICBhdCBTeXN0ZW0uUnVudGltZU1ldGhvZEhhbmRsZS5JbnZva2VNZXRob2QoT2JqZWN0IHRhcmdldCwgU3BhbmAxJiBhcmd1bWVudHMsIFNpZ25hdHVyZSBzaWcsIEJvb2xlYW4gY29uc3RydWN0b3IsIEJvb2xlYW4gd3JhcEV4Y2VwdGlvbnMpXHJcbiAgIGF0IFN5c3RlbS5SZWZsZWN0aW9uLlJ1bnRpbWVDb25zdHJ1Y3RvckluZm8uSW52b2tlKE9iamVjdCBvYmosIEJpbmRpbmdGbGFncyBpbnZva2VBdHRyLCBCaW5kZXIgYmluZGVyLCBPYmplY3RbXSBwYXJhbWV0ZXJzLCBDdWx0dXJlSW5mbyBjdWx0dXJlKVxyXG4gICBhdCBEYWxhbXVkLklvQy5JbnRlcm5hbC5TZXJ2aWNlQ29udGFpbmVyLkNyZWF0ZUFzeW5jKFR5cGUgb2JqZWN0VHlwZSwgT2JqZWN0W10gc2NvcGVkT2JqZWN0cykgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW9DXFxJbnRlcm5hbFxcU2VydmljZUNvbnRhaW5lci5jczpsaW5lIDEwN1xyXG4gICBhdCBEYWxhbXVkLlBsdWdpbi5JbnRlcm5hbC5UeXBlcy5Mb2NhbFBsdWdpbi5Mb2FkQXN5bmMoUGx1Z2luTG9hZFJlYXNvbiByZWFzb24sIEJvb2xlYW4gcmVsb2FkaW5nKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxQbHVnaW5cXEludGVybmFsXFxUeXBlc1xcTG9jYWxQbHVnaW4uY3M6bGluZSA0MTZcclxuICAgYXQgRGFsYW11ZC5QbHVnaW4uSW50ZXJuYWwuUGx1Z2luTWFuYWdlci5Mb2FkUGx1Z2luQXN5bmMoRmlsZUluZm8gZGxsRmlsZSwgTG9jYWxQbHVnaW5NYW5pZmVzdCBtYW5pZmVzdCwgUGx1Z2luTG9hZFJlYXNvbiByZWFzb24sIEJvb2xlYW4gaXNEZXYsIEJvb2xlYW4gaXNCb290LCBCb29sZWFuIGRvTm90TG9hZCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcUGx1Z2luTWFuYWdlci5jczpsaW5lIDc5MlxyXG4gICBhdCBEYWxhbXVkLlBsdWdpbi5JbnRlcm5hbC5QbHVnaW5NYW5hZ2VyLkluc3RhbGxQbHVnaW5Bc3luYyhSZW1vdGVQbHVnaW5NYW5pZmVzdCByZXBvTWFuaWZlc3QsIEJvb2xlYW4gdXNlVGVzdGluZywgUGx1Z2luTG9hZFJlYXNvbiByZWFzb24pIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcSW50ZXJuYWxcXFBsdWdpbk1hbmFnZXIuY3M6bGluZSA3NDUiLCJDb250ZXh0IjoiW1BMVUdJTlddIFBsdWdpbiBpbnN0YWxsZXIgdGhyZXcgYW4gdW5leHBlY3RlZCBlcnJvciJ9
2022-08-28 00:09:31.379 +08:00 [ERR] [PLUGINW] Plugin installer threw an unexpected error
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Collections.Generic.KeyNotFoundException: Can't find a signature of 48 8B 01 38 50 0C 
   at Dalamud.Game.SigScanner.ScanText(String signature) in C:\goatsoft\companysecrets\dalamud\Game\SigScanner.cs:line 310
   at Lock.Plugin..ctor(DalamudPluginInterface pluginInterface, Framework framework, CommandManager commandManager, SigScanner sigScanner, ClientState clientState)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects) in C:\goatsoft\companysecrets\dalamud\IoC\Internal\ServiceContainer.cs:line 107
   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\LocalPlugin.cs:line 416
   at Dalamud.Plugin.Internal.PluginManager.LoadPluginAsync(FileInfo dllFile, LocalPluginManifest manifest, PluginLoadReason reason, Boolean isDev, Boolean isBoot, Boolean doNotLoad) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 792
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 745
```

**Comment by tssailzz8** [comment]
are you use net7?

**Comment by jacky50403** [comment]
Do you mean this one?
```
C:\Users\user>dotnet --list-sdks
6.0.202 [C:\Program Files\dotnet\sdk]
```
If I was wrong please correct me

**Comment by tssailzz8** [comment]
in Global you should use https://raw.githubusercontent.com/tssailzz8/MyPlugins/net7/pluginmaster.json

**Comment by jacky50403** [comment]
Thank you
Can you tell me what these options are btw
![image](https://user-images.githubusercontent.com/46365568/187354598-ee04121f-f019-415d-8c1d-fc81d8fdcba0.png)
I can't see them since Dalamud is missing Chinese font
